Implement Lazy Matching
SwiftAlgorithmClub/AGString pull request #17
Opened 2019-11-11 11:59 UTC by JCSooHwanCho

지연 매칭을 구현하였습니다.

1. AGMatchLazyList, AGMatchLazyListIterator 추가
2. matchAllLazily 메소드 추가, 이전에 삭제되었던 findIter를 대체함

2019-11-11 14:52 UTC, kimtaesu commented on Sources/Regex/AGMatchLazyList.swift
> +    public let baseString: String
`private`  접근 제어자가 좋을 것 같습니다~

2019-11-11 14:58 UTC, kimtaesu commented on Sources/Regex/AGMatchLazyList.swift
> +    init(withBase base: String, regex: NSRegularExpression) {
`withBase` -> `base` 로 전에 쓰기로 결정했습니다.

2019-11-11 15:01 UTC, JCSooHwanCho commented on Sources/Regex/AGMatchLazyList.swift
> +    public let baseString: String
AGMatchList에서는 base가 public입니다. AGMatch 자체만으로는 의미가 없고 원본 문자열을 함께 참조할 수 있어야 한다는 의도여서 public을 유지하는 것은 어떨까합니다.

2019-11-11 15:02 UTC, JCSooHwanCho commented on Sources/Regex/AGMatchLazyList.swift
> +    init(withBase base: String, regex: NSRegularExpression) {
이 부분은 놓쳤네요. 수정하겠습니다.

2019-11-11 15:02 UTC, kimtaesu commented on Sources/Regex/AGRegex.swift
> +    public func matchAllLazliy (_ str: String,
띄어쓰기가 있습니다.

2019-11-11 15:03 UTC, JCSooHwanCho commented on Sources/Regex/AGRegex.swift
> +    public func matchAllLazliy (_ str: String,
수정하겠습니다!

2019-11-11 15:08 UTC, kimtaesu commented on Sources/Regex/AGRegex.swift
> +    public func matchAllLazliy (_ str: String,
`Lazliy` 부사나 형용사보다는 `matchIterator`  Naming 은 어떨까요?

![image](https://user-images.githubusercontent.com/20927825/68597526-775d2580-04e0-11ea-908b-1fc40ed66627.png)

2019-11-11 15:09 UTC, kimtaesu requested changes
Naming 관련해서 드립니다~

2019-11-11 15:09 UTC, kimtaesu commented on Sources/Regex/AGMatchLazyList.swift
> +    public let baseString: String
넵 getter 의 역할이라면 좋습니다~

2019-11-11 15:11 UTC, kimtaesu commented on Sources/Regex/AGRegex.swift
> +    public func matchAllLazliy (_ str: String,
근데 이게 좀.. 앞이냐 뒤에 차이인데..
`Also, never use adverbs or adjectives before the verb.`

2019-11-11 15:12 UTC, kimtaesu commented on Sources/Regex/AGRegex.swift
> +    public func matchAllLazliy (_ str: String,
이부분은 어떻게 생각하시나요?

2019-11-11 15:12 UTC, kimtaesu commented on Sources/Regex/AGRegex.swift
> +    public func matchAllLazliy (_ str: String,
https://developer.apple.com/library/archive/documentation/Cocoa/Conceptual/CodingGuidelines/Articles/NamingMethods.html#//apple_ref/doc/uid/20001282-BCIGIJJF

2019-11-11 15:32 UTC, JCSooHwanCho commented on Sources/Regex/AGRegex.swift
> +    public func matchAllLazliy (_ str: String,
일단 저 함수가 반환하는게 Iterator가 아니여서 Iterator를 이름에 넣는 건 부적절합니다.
제 의도는 AGMatchList인데, Lazy하게 그때 그때 값을 완성하는 또 다른 AGMatchList였어서 네이밍을 저렇게 했는데 좀 더 수정할 여지가 있는 것 같습니다.

2019-11-12 02:39 UTC, JCSooHwanCho commented on Sources/Regex/AGRegex.swift
> +    public func matchAllLazliy (_ str: String,
makeMatchStream 이라는 이름을 적용해보았습니다.

2019-11-12 07:48 UTC, merged